// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Fonts fonts = _Fonts._();
  static final _Icons icons = _Icons._();
  static final _Images images = _Images._();
  static final _Lang lang = _Lang._();
}

@immutable
final class _Fonts {
  _Fonts._();

  final String manrope_bold_ttf = 'assets\fonts\Manrope-Bold.ttf';
  final String manrope_light_ttf = 'assets\fonts\Manrope-Light.ttf';
  final String manrope_medium_ttf = 'assets\fonts\Manrope-Medium.ttf';
  final String manrope_regular_ttf = 'assets\fonts\Manrope-Regular.ttf';
  final String manrope_semibold_ttf = 'assets\fonts\Manrope-SemiBold.ttf';
}

@immutable
final class _Icons {
  _Icons._();
}

@immutable
final class _Images {
  _Images._();

  final String logo_svg = 'assets/images/logo.svg';
  final String onboarding_1_png = 'assets/images/onboarding_1.png';
  final String onboarding_2_png = 'assets/images/onboarding_2.png';
  final String onboarding_3_png = 'assets/images/onboarding_3.png';
}

@immutable
final class _Lang {
  _Lang._();

  final String ar_json = 'assets\lang\ar.json';
  final String en_json = 'assets\lang\en.json';
}
